# This example demonstrates distributed reinforcement learning training using veRL framework
# Training a DeepSeek-LLM-7B-Chat model on GSM8K and MATH datasets using GRPO algorithm

entrypoint: "python main_multidata.py"
submission_id: "verl_grpo_training"
shutdown_after_job_finishes: True
ray_cluster_spec:
  attribution:
    project: LLM-Abstraction
    development_type: training
    foundation_model: false
    model_type: text
    model_size: 7B
    spend: dev
  cluster_name: "veRL GRPO Training - DeepSeek 7B (on Nvidia B200)"
  ray_version: 2.51.0
  heartbeat_timeout_s: 300
  idle_timeout_minutes: 60
  upscaling_speed: 1000
  runtime_env_activation_command: ":"
  setup_command: bash setup-b200.sh
  head_node_type: head
  resources:
    docker_image: docker.apple.com/bolt/cuda:12.8.1-python3.10.11-ubuntu22.04
    cluster: aws_9
    ports:
      - HTTP_API
  environment_variables:
    WANDB_API_KEY: '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'
    FI_EFA_FORK_SAFE: '1'
    FI_EFA_USE_DEVICE_RDMA: '1'
    FI_PROVIDER: efa
    LD_LIBRARY_PATH: /opt/amazon/efa/lib:/opt/amazon/openmpi/lib:/opt/amazon/ofi-nccl/lib/x86_64-linux-gnu
    NCCL_BUFFSIZE: '8388608'
    NCCL_DEBUG: INFO
    NCCL_TUNER_PLUGIN: libnccl-ofi-tuner.so
    NCCL_IGNORE_DISABLED_P2P: '1'
    PATH: /opt/amazon/openmpi/bin:$PATH
    UCX_LOG_LEVEL: debug
  roles:
    worker:
      resources:
        task_type: 8gpu
        max_node: 4
        min_node: 4
        rdma: true
      cluster_options:
        aws:
          instance_type: p6-b200.48xlarge
    head:
      resources:
        task_type: 8cpu
        max_node: 0
        min_node: 0
      ray_start_params:
        num-cpus: "0"
  project_id: mlr_s_gatmiry
